# Generated by Django 2.0.6 on 2018-06-13 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses_taken',
            new_name='CoursesTaken',
        ),
        migrations.RenameField(
            model_name='coursestaken',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='coursestaken',
            old_name='Grade',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='Degree',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='Institution',
            new_name='institution',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='Project_name',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='Technologies_used',
            new_name='technologies_used',
        ),
        migrations.RemoveField(
            model_name='education',
            name='Grad',
        ),
        migrations.RemoveField(
            model_name='education',
            name='Grades',
        ),
        migrations.AddField(
            model_name='education',
            name='graddate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Graduation Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='grades',
            field=models.DecimalField(decimal_places=3, default=3.416, max_digits=5),
            preserve_default=False,
        ),
    ]
