# Generated by Django 2.0.6 on 2018-06-13 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20180612_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestaken',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cv.Education'),
            preserve_default=False,
        ),
    ]
