# Generated by Django 2.0.6 on 2018-06-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_coursestaken_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('level', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
